### ISSUE TITLE
Complete readme informations and add makefile

### ISSUE THREAD

**Issue by kevin-schmitt** [SplashSync/Tasking-Bundle#2]
Hello,

Is possible to complete readme with more information:
- Installation with docker (i saw docker-compose file)
- Todo of next task (for contributor)

Makefile for run test or installation quickly.

Thanks

**Comment by BadPixxel** [comment]
Hi,

For sure, this is in my road map for next release.
Docker is only for running tests but I'll document this too.

Thanks for you interest in this project! We made this bundle for our needs, now it's stable and rugged... Could be really useful for Sf community.

Best regards

**Comment by BadPixxel** [comment]
@kevin-schmitt I've pushed a more detailled documentation. Let me know if I missed something.
